REM SET JAVA_HOME=C:\DEV\SDK\JDK\jdk-11.0.9
SET JAVA_HOME=C:\DEV\SDK\JDK\jdk1.8.0_131
SET MVN_HOME=C:\DEV\Tools\apache-maven-3.6.3
SET NODE_HOME=C:\DEV\Tools\nodejs
SET KAFKA_HOME=C:\DEV\Tools\kafka_2.13-2.7.0
SET JASYPT_HOME=C:\DEV\Tools\jasypt-1.9.3
SET PROJ_HOME=C:\DEV\Deploy\CloudLvl2_3
SET ANACONDA_HOME=C:\DEV\SDK\Anaconda3
SET MONGO_HOME=C:\DEV\Tools\mongodbb
@REM SET MONGO_HOME=C:\DEV\Tools\Database\mongodb-win32-x86_64-windows-4.4.4
@REM SET MARIA_HOME=C:\DEV\Tools\Database\mariadb-10.3.13-winx64
SET MARIA_HOME=C:\DEV\Tools\mariadb-10.3.13-winx64
SET MARIA_DATA=C:\DEV\DATA\mariadb


SET PATH=%MARIA_HOME%\BIN;%MONGO_HOME%\BIN;%NODE_HOME%;%NODE_HOME%\node_modules\npm;%NODE_HOME%\node_modules;%KAFKA_HOME%\BIN\WINDOWS;%JAVA_HOME%\BIN;%MVN_HOME%\BIN;%PATH%;